"""rights user

Revision ID: f7cac22d3416
Revises: 50615ee39399
Create Date: 2023-11-30 10:25:59.546726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cac22d3416'
down_revision: Union[str, None] = '50615ee39399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('right_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'right', ['right_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'right_id')
    # ### end Alembic commands ###
